### ISSUE TITLE
Design of webapp

### ISSUE THREAD

**Issue by nichoth** [planetary-social/webapp#2]
Here's the visual design -- https://planetary-online.webflow.io/

see the source here — https://github.com/planetary-social/ssb-viewer

slack discussion —
https://planetary-app.slack.com/archives/CE6RE5400/p1636758392002600

![image.png](https://zube.io/files/planetary-2/c4aa401c51f15abf9b4e2447bc5032ec-image.png)

**Comment by nichoth** [comment]
* [ ] learn if the user already has an ID, and vary the page depending

**Comment by nichoth** [comment]
* need assets/figma from @Chardot , for the logo

**Comment by Chardot** [comment]
@nichoth Here's the WIP on Figma https://www.figma.com/file/6oTsbY3vHME19RNtgSGdAw/Planetary-Design-Plan?node-id=1%3A3
